### ISSUE TITLE
Crop Names

### ISSUE THREAD

**Issue by colinbendell** [universalimages/rmd#1]
A colloquial name is needed to differentiate between crop zone sets. Specifically an image usually has multiple different use cases (eg: search results, banner ad, product detail, etc) in addition to art direction responsive images. That is, an image might have a square crop for search results, but have different square crop widths for different media queries. An image transformation service would both select the use case set and then subsequently filter based on the appropriate responsive images directives. To do this we need to add a name or ID notation to the crop zone.

**Comment by sbaechler** [comment]
Hi Colin

Could you give a concrete example for this feature?
It is currently possible to have different square crop widths for different media queries. 

The current standard is based on the assumption that the crop is only defined by the physical size of the image. I could not think of a use case where there was no linear correlation between the size of the image and the size of the crop. Could you give an example where this is reversed?

An interesting but complex extension would be to allow crops based on context.
Take for instance this [image of a group of hikers on a glacier covered in white sheets in Switzerland](http://www.keystone.ch/bild-disp/diasdb/KEYSTONE_262547205.jpg?w=true) :
There are two possible context: One is glacial melting which, one is tourism.

**Comment by colinbendell** [comment]
Take for example, the times square autograph hotel: [search](http://exp.cdn-hotels.com/hotels/1000000/30000/25800/25764/25764_119_z.jpg) [result](https://cache.marriott.com/propertyimages/n/nycak/nycake01.jpg) and [landing](https://cache.marriott.com/propertyimages/n/nycak/nycak_main01_r.jpg) [page](https://cache.marriott.com/propertyimages/n/nycak/nycak_main01_r.jpg?resize=183:*). As you can see the search result is square and the landing is a wide form. You can see the images in context: [Search results](https://www.marriott.com/search/submitSearch.mi?searchType=InCity&groupCode=&searchRadius=&poiName=&poiCity=&recordsPerPage=20&for-hotels-nearme=Near&destinationAddress.destination=New+York%2C+NY%2C+USA&singleSearch=true&singleSearchAutoSuggest=true&autoSuggestItemType=Unmatched&clickToSearch=false&destinationAddress.latitude=40.753489&destinationAddress.longitude=-73.980961&destinationAddress.cityPopulation=8405837.0&destinationAddress.cityPopulationDensity=0.0&destinationAddress.city=New+York&destinationAddress.stateProvince=NY&destinationAddress.country=US&airportCode=&fromToDate=Wed%2C+May+4%2C+2016&fromToDate_submit=05%2F04%2F2016&fromDate=05%2F03%2F2016&toDate=05%2F04%2F2016&lengthOfStay=1&roomCountBox=1&roomCount=1&guestCountBox=1&guestCount=1&clusterCode=none&corporateCode=) and [landing page](https://www.marriott.com/hotels/travel/nycak-the-algonquin-hotel-times-square-autograph-collection/))

The assumption here is that the resize is handled by srcset or Client-Hints or other content-negotiation techniques. However, the selection of the correct crop is based on context. Both would have the same min-width media query but because they have different heights we need a different way to identify the correct crop.

**Comment by sbaechler** [comment]
Hi Colin

I see your point, but what you describe is currently possible with the way the recommended crops work.
You can define multiple 'recommended' crops with different aspect ratio and size constraints. So if the client asks for a portrait version of the image then the frame that matches that is used. The selection works by comparing the image area for the best match. 

In your example the question remains, if it is really the context that should define the crop or is it just the size and aspect ratio. I think in this case it is just the size and aspect ratio.

Have a look a the [example page](http://sbaechler.github.io/universalimages-demo/). There I defined a square region that is used whenever the requested crop has a square aspect ratio.
